### ISSUE TITLE
Install-module from Find-Module

### ISSUE THREAD

**Issue by alanrenouf** [PoshCode/PoshCode#6]
So i started playing with this and started with find-module which works great, I then narrowed it down and tried to install a found module, it didn't work, would be cool if this worked:

Find-Module -ModuleName VisioAutomation | Install-Module

**Comment by Jaykul** [comment]
Yeah, that _should_ work.

**Comment by Jaykul** [comment]
This is fixed now, I think with all the repos, but definitely with chocolatey ;)
